### ISSUE TITLE
Chrome extension stuck on version 1.5.2

### ISSUE THREAD

**Issue by mcbyte-it** [stylish-userstyles/stylish-chrome#190]
Everything was working fine, until today when I installed the extension to a new Chrome profile, and I noticed the different icon. investigating I found that my main profile (with many userstyles in it) is still on version 1.5.2, when the latest Stylish extension version is 1.6.3.

How can I force upgrade the extension without loosing my styles? v1.7 should introduce backup, but on 1.5.2 what can i do?

**Comment by guraga** [comment]
To upgrade all extensions of "google chrome" do following actions:
* open page "chrome://extensions/";
* set check box "Developer mode";
* press button "Update extensions now";
* wait some time.

**Comment by mcbyte-it** [comment]
it was frozen before, now it works and it got updated
