### ISSUE TITLE
Add some feature to custom style sheet for chrome extension self?

### ISSUE THREAD

**Issue by qwIvan** [stylish-userstyles/stylish-chrome#197]
Custom popup page and manager page.
chrome-extension://fjnbnpbmkenffdnngjfgmeleoegfcffe/manage.html

**Comment by tophf** [comment]
It's already implemented, see the [existing themes](https://userstyles.org/styles/browse/chrome-extension).

Such style should contain:

* A dummy section with a specially crafted invalid URL exactly as shown below to be recognized on userstyles.org site
* Style sections for the `popup.html` or `manage.html` declared using regexp

	~~~css
	@-moz-document url("http://chrome-extension://fjnbnpbmkenffdnngjfgmeleoegfcffe/manage.html") {}

	@-moz-document regexp("chrome-extension://.*?/manage.html") {

	/* your CSS here */

	}
	~~~

You can import this template by clicking the `Import` button on the Edit page after creating a new style.

![clip199-fs8](https://cloud.githubusercontent.com/assets/1310400/23200396/284231e8-f8e5-11e6-980f-9fe66b4c3bec.png)

**Comment by qwIvan** [comment]
thanks
