### ISSUE TITLE
Add an editor preference for the 'scroll into view' behavior

### ISSUE THREAD

**Issue by hideheader** [stylish-userstyles/stylish-chrome#71]
Scrolling the window so that the cursor is visible is great. Scrolling the window when the cursor is already visible is really, *really* annoying. That latter behavior should be attached to a preference, and disabled by default.

**Comment by tophf** [comment]
What about limiting the scroll-into-view behavior to a few cases where it is expected:
1. Switching between sections via Alt-PgUp/PgDn
2. Searching

**Comment by tophf** [comment]
Fixed, presumably.
